[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.gd", "php83Extensions.mbstring", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.redis"]

[phases.build]
cmds = ["mkdir -p /tmp && chmod 777 /tmp"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t /app"
